-- Portable DDL: runs unchanged on H2 (2.x) and PostgreSQL (10+)
CREATE TABLE IF NOT EXISTS person (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    title      VARCHAR(255)
);
